name: Manual matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        include:                # manually definition
          - os: ubuntu-latest   # pattern 1
            version: 20
          - os: macos-latest    # pattern 2
            version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version
